### ISSUE TITLE
Erreur d'installation

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature-GIS#39]
Bonjour,

Je viens d'essayer d'installer ce plugin en suivant la méthode d'installation indiquée dans la documentation. J'ai d'abord reçu ce message d'erreur :

![erreur_installation1](https://github.com/PnX-SI/GeoNature-GIS/assets/68049696/9ce80998-976e-4645-b327-4ce976255a64)

Après avoir cliqué sur "Ok", je reçois le message d'erreur suivant : 
```
Impossible de charger l'extension 'GeoNature-GIS-1.1.1' 

ModuleNotFoundError: No module named 'GeoNature-GIS-1' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'GeoNature-GIS-1'


Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.28.11-Firenze Firenze, b02458a196 
```

Le plugin apparaît ensuite dans la liste de plugins, mais il est désactivé. Lorsque je souhaite l'activer, je reçois le même message d'erreur qu'indiqué ci-dessus. Je remarque par ailleurs que la version du plugin installée est la 1.0.0 alors que cela devrait être la version 1.1.1 ?

J'ai essayé également de dézipper le fichier dans mon dossier de plugins QGIS `profiles\default\python\plugins` : cela produit la même erreur.

Merci pour votre travail !

**Comment by JulesGrillot** [comment]
Pour la fenêtre des dépendances cela vient de la dernière ligne du fichier metadata.txt.
Comme stipuler dans la [documentation QGIS](https://docs.qgis.org/3.34/fr/docs/pyqgis_developer_cookbook/plugins/plugins.html#metadata-txt)

`; Since QGIS 3.8, a comma separated list of plugins to be installed
; (or upgraded) can be specified.
; The example below will try to install (or upgrade) "MyOtherPlugin" version 1.12
; and any version of "YetAnotherPlugin".
; Both "MyOtherPlugin" and "YetAnotherPlugin" names come from their own metadata's
; name field
plugin_dependencies=MyOtherPlugin==1.12,YetAnotherPlugin`

Ce bloc permet de dire lors de l'installation qu'il existe des dépendance nécessaires à installer pour utiliser le plugin. En l’occurrence `MyOtherPlugin` version 1.12 et `YetAnotherPlugin`

Cette dépendance est d'ailleurs visible ici :
![image](https://github.com/PnX-SI/GeoNature-GIS/assets/37152611/8a569da1-4dde-4560-8073-ac3fb8aa303f)


Supprimer cette ligne du fichier metadata.txt devrait résoudre le problème :
`plugin_dependencies=MyOtherPlugin==1.12,YetAnotherPlugin`

**Comment by JulesGrillot** [comment]
Pour l'autre erreur, elle apparaît car vous avez utilisé le zip de la release 1.1.1. 

Dans la [doc d'installation](https://github.com/PnX-SI/GeoNature-GIS/blob/main/help/installation.md) il est montré comment installé directement la branche `main`, ce qui fonctionne.

**Comment by maximetoma** [comment]
Bonjour,
Effectivement, il reste une coquille, je l'ai supprimée de la branche main et ai modifié le fichier metadata.txt

**Comment by camillemonchicourt** [comment]
Ça vaut le coup de sortir une 1.1.2 avec ces corrections, non ?

**Comment by camillemonchicourt** [comment]
Corrigé dans la 1.1.2

**Comment by geobrun** [comment]
Merci pour les explications et les corrections ! :)
